### ISSUE TITLE
Configure this CMake to be able to edit the OpenSSL code in Visual Studio

### ISSUE THREAD

**Issue by oliviervibe** [jimmy-park/openssl-cmake#1]
Hi,

This is not an issue as your CMake perfectly works.

I'm integrating a new signature algorithm into OpenSSL. I already did it for OpenSSL 1.1.1 using the openssl-cmake project of janbar. However, his project doesn't support OpenSSL 3 and I need to move to this version.

I thought I could use yours, but as it pulls the OpenSSL code from the original openssl git it produces a Visual Studio solution that doesn't allow editing the code!

I pulled the code of OpenSSL from the official git. Is there a way to integrate your CMake with the local code to create a Visual Studio solution where the code of OpenSSL can be edited?

Thanks for your help.

**Comment by jimmy-park** [comment]
@oliviervibe Since this repo is CMake scripts for building OpenSSL, OpenSSL sources aren't included in the generated project. I couldn't do that because OpenSSL's build system depends heavily on perl scripts. The generated project is just for `apps/main.cpp`, not the OpenSSL source itself. You need to use another editor such as vscode.

For building local OpenSSL sources, you need to change the following code to locate your own source.
https://github.com/jimmy-park/openssl-cmake/blob/6719ec98b17e4d4ec7b9795ca5c18f99d89ab14f/CMakeLists.txt#L62-L75

If you have forked OpenSSL repo, changing `URL` is enough. If not, remove `CPMAddPackage()` and change `SOURCE_DIR/BINARY_DIR`.

**Comment by oliviervibe** [comment]
Thanks for your quick answer! 
I saw your comment in the github of janbar regarding OpenSSL 3.0. So I'll try to do what you said and do it with VScode. My current version of OpenSSL with our crypto is based on the OpenSSL with cmake of janbar, and I have both a Linux and a Windows version as we currently call our crypto from a shared library.

**Comment by jimmy-park** [comment]
@oliviervibe Thanks for understanding!
